src/StakingManager.sol, test/DepositAndWithdraw.t.sol
- Add test coverage for live bridge
95%+ test coverage on in scope files
https://app.warp.dev/block/OAsx54tb5wa8yk6LTgS3GU
=> Test coverage

src/EdgelessDeposit.sol, src/StakingManager.sol
https://www.notion.so/veridise/UPDATED-Typos-and-incorrect-comments-ba508e6d83fe449b88c57e9e7cabcd14?pvs=4
=> ✅Fix typos

src/WrappedToken.sol
https://www.notion.so/veridise/Variable-could-be-immutable-78806a9e71df4ba78f3e02cf3042c328?pvs=4
=> ✅Make variable immutable

src/strategies/EthStrategy.sol
https://www.notion.so/veridise/Unchecked-approve-de530777537d4e8593596343d59b4c2c?pvs=4
=> ✅Check approve lido

src/StakingManager.sol, test/AdminTests/AdminSetVariables.t.sol
https://www.notion.so/veridise/Removing-strategy-may-pause-contract-12e8fe77ecaf47729f29c5de8b2f068c?pvs=4
=> ✅Add staking manager

src/strategies/EthStrategy.sol
https://www.notion.so/veridise/Code-duplication-7435a0adaa4f42069654f6150eea5363?pvs=4
=> ✅Add internal functions to lower code duplication

src/StakingManager.sol
https://www.notion.so/veridise/Fund-recovery-after-strategy-removal-requires-full-shutdown-106fe46f8cfe46608fcae0fa9a8f8f23?pvs=4
=> ✅Remove auto withdrawal, add withdrawToStaker

src/ForceCompile.sol
https://www.notion.so/veridise/Compiler-warning-in-ForceCompile-sol-6d04c61b5d804e5a85c3a60e020565f2?pvs=4
=> ✅Add compiler version

src/interfaces/ILido.sol, src/strategies/EthStrategy.sol
https://www.notion.so/veridise/Incorrect-Lido-interface-function-7d1447f6cbfb4f9cbf7682a4b3455c02?pvs=4
https://www.notion.so/veridise/Unused-submit-return-value-6a351c7a47014b9398420ace8fa778ac?pvs=4
=> ✅Add sharesGeneratedEvent when calling lido.submit

src/strategies/EthStrategy.sol
https://www.notion.so/veridise/override-keyword-unused-7868f85d659748a0912b74e6b1581406?pvs=4
=> ✅Add override

src/EdgelessDeposit.sol, src/StakingManager.sol
https://www.notion.so/veridise/Staking-manager-withdrawal-amount-unchecked-74b24f8d275349fc9a73c89b9cf7493f?pvs=4
=> ✅Add return value to stakingManager.withdraw and check in withdrawEth

src/StakingManager.sol, test/AdminTests/AdminSetVariables.t.sol
https://www.notion.so/veridise/Strategies-may-be-duplicates-ba04aa5d9ded453f89fad31f24f79bc6?pvs=4
=> Unusable strategies may be added

src/StakingManager.sol, test/AdminTests/AdminSetVariables.t.sol
https://www.notion.so/veridise/Strategies-may-be-duplicates-ba04aa5d9ded453f89fad31f24f79bc6?pvs=4
=> ✅Add check and fix tests

src/StakingManager.sol, test/AdminTests/AdminSetVariables.t.sol
https://www.notion.so/veridise/No-range-check-on-active-strategy-25dc7f86ab98461bb496ece502904e00?pvs=4
=> ✅make sure index is less than activeStrategyIndex[asset]

src/StakingManager.sol
https://www.notion.so/veridise/Wrong-amount-emitted-on-stake-398aae608add4e09878fc198d20d55d5?pvs=4
=> ✅Fix stakeEth amount

src/EdgelessDeposit.sol, src/StakingManager.sol, src/strategies/EthStrategy.sol
https://www.notion.so/veridise/Initializable-best-practices-46fa491cf4244076b382d9a078915123?pvs=4
=> Initializable best practices

package-lock.json, package.json, src/EdgelessDeposit.sol, src/StakingManager.sol, src/interfaces/IWithdrawalQueueERC721.sol, test/AdminTests/AdminSetVariables.t.sol
https://www.notion.so/veridise/Unused-program-constructs-ae1bbec87326465b826b6aadcad2dcc4?pvs=4
=> Unused program constructs

src/StakingManager.sol, src/interfaces/IWithdrawalQueueERC721.sol
https://www.notion.so/veridise/Removing-strategy-may-pause-contract-12e8fe77ecaf47729f29c5de8b2f068c?pvs=4
=> Removing strategy may pause contract fix

src/StakingManager.sol
https://www.notion.so/veridise/Fund-recovery-after-strategy-removal-requires-full-shutdown-106fe46f8cfe46608fcae0fa9a8f8f23?pvs=4
=> Fund recovery after strategy removal requires full shutdown

src/EdgelessDeposit.sol, src/StakingManager.sol, test/AdminTests/AdminSetVariables.t.sol
https://www.notion.so/veridise/Wrong-amount-emitted-on-stake-398aae608add4e09878fc198d20d55d5?pvs=4
=> ✅Fix amount emitted on stake

src/StakingManager.sol
https://www.notion.so/veridise/Strategies-may-be-duplicates-ba04aa5d9ded453f89fad31f24f79bc6?pvs=4
=> ✅Track all strategies

src/StakingManager.sol
https://www.notion.so/veridise/Removing-strategy-may-pause-contract-12e8fe77ecaf47729f29c5de8b2f068c?pvs=4
=> ✅Add new strategy index check and add event
